## Comment what you need
git push origin :translations/cm-14.1
git push origin :themes-exp
git push origin :staging/cm-13.0+r22
git push origin :staging/cm-12.1
git push origin :staging/cm-12.0-caf
git push origin :stable/cm-13.0-ZNH5Y
git push origin :stable/cm-13.0-ZNH2KB
git push origin :stable/cm-13.0-ZNH2K
git push origin :stable/cm-13.0-ZNH0E
git push origin :stable/cm-12.1-YOG7D
git push origin :stable/cm-12.1-YOG4P
git push origin :stable/cm-12.1-YOG3C
git push origin :stable/cm-12.0-YNG4N
git push origin :stable/cm-12.0-YNG3C
git push origin :stable/cm-12.0-YNG1TA
git push origin :stable/cm-12.0-YNG1T
git push origin :stable/cm-12.0-YNG1I
git push origin :stable/cm-11.0
git push origin :stable/cm-11.0-XNG3C
git push origin :stable/cm-11.0-XNG2S
git push origin :stable/cm-11.0-XNF9X
git push origin :stable/cm-11.0-XNF8Y
git push origin :stable/cm-10.2
git push origin :shipping/cm-11.0
git push origin :mr1.1-staging
git push origin :lineage-15.0
git push origin :jellybean
git push origin :jellybean-stable
git push origin :ics
git push origin :ics-release
git push origin :gingerbread
git push origin :gingerbread-release
git push origin :gb-release-7.2
git push origin :froyo
git push origin :froyo-stable
git push origin :eclair
git push origin :cm-14.1
git push origin :cm-14.0
git push origin :cm-13.0
git push origin :cm-12.1
git push origin :cm-12.0
git push origin :cm-11.0
git push origin :cm-10.2
git push origin :cm-10.1
git push origin :cm-9.1.0
git push origin :cm-7.0.3
git push origin :cm-7.0.2.1
git push origin :cm-7.0.1
git push origin :cm-7.0.0